services:
  app:
    # image: pedestal-component:latest # Replace with your actual image name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8890:8890"
    env_file:
      - .env # Pass variables from the .env file to the container
    # or via environment variables
    # environment:
    #   WS_PORT: 6666
    restart: always
